name: erichcamping
favicon: null
layout_spectrum: 0.06176
typography_spectrum: 0.7212021788582206
title: rochester ny photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffb200'
    - '#918474'
    - '#dbd6cd'
    - '#bcb2a9'
  brandStrength: 0.9375
  lightness: 0.31461562728509307
  saturation: 0.375
  rhythmicContrast: 0.75
purpose: []
